---
- name: Get Version from checkout if not provided
  shell: "git describe --long | sed 's/\\-g.*//' | sed 's/\\-/\\./'"
  delegate_to: localhost
  register: awx_version_command
  when: awx_version is not defined

- name: Set global version if not provided
  set_fact:
    awx_version: "{{ awx_version_command.stdout }}"
  when: awx_version is not defined

- name: Set sdist file name
  set_fact:
    awx_sdist_file: "awx-{{ awx_version }}.tar.gz"
    
- name: Stat distribution file
  stat:
    path: "../dist/{{ awx_sdist_file }}"
  delegate_to: localhost
  register: sdist

- name: Set docker build base path
  set_fact:
    docker_base_path: "{{ awx_local_base_config_path|default('/tmp') }}/docker-image"

- name: Set awx_web image name
  set_fact:
    awx_web_image: "{{ awx_web_image|default('awx_web') }}"

- name: Set awx_task image name
  set_fact:
    awx_task_image: "{{ awx_task_image|default('awx_task') }}"

- name: Build base web image
  docker_image:
    path: "{{ docker_base_path }}"
    dockerfile: Dockerfile
    name: "{{ awx_web_image }}"
    tag: "{{ awx_version }}"
  delegate_to: localhost

- name: Build base task image
  docker_image:
    path: "{{ docker_base_path }}"
    dockerfile: Dockerfile.task
    name: "{{ awx_task_image }}"
    tag: "{{ awx_version }}"
    pull: no
  delegate_to: localhost

- name: Clean docker base directory
  file:
    path: "{{ docker_base_path }}"
    state: absent
  when: cleanup_docker_base|default(True)
  delegate_to: localhost
