---
- name: Build and deploy AWX
  hosts: all
  gather_facts: false
  vars:
    awx_local_base_config_path: ./build
  roles:
    - { role: check_vars }
    - { role: image_build }
    - { role: openshift, when: "openshift_host is defined" }
    - { role: local_docker, when: "openshift_host is not defined" }

